language: php
php:
  - "5.6"

services:
  - mongodb

env:
  - PECLMONGO=mongo-1.6.10

before_install:
  - sudo apt-get update > /dev/null
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  # install Mongo extension
  - sh -c "wget http://pecl.php.net/get/$PECLMONGO.tgz"
  - sh -c "tar xfz $PECLMONGO.tgz"
  - sh -c "cd $PECLMONGO && phpize && ./configure && make && sudo make install"

  - phpenv config-add .travis/phpenv.ini
  - curl -sS https://getcomposer.org/installer | php
  - ./composer.phar self-update
  - ./composer.phar create-project --stability dev cross-solution/yawik=dev-develop ../yawik
  - mv ../`basename $TRAVIS_BUILD_DIR` `dirname $TRAVIS_BUILD_DIR`/yawik/module

script:
  - cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/JobsByMail/test
  - phpunit

after_script:
  - cd `dirname $TRAVIS_BUILD_DIR`/yawik/module/JobsByMail
  - php `dirname $TRAVIS_BUILD_DIR`/yawik/vendor/bin/coveralls -vvv
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.serialized
