<?php
/**
 * YAWIK
 *
 * @filesource
 * @copyright (c) 2013 - 2017 Cross Solution (http://cross-solution.de)
 * @license   MIT
 * @author    bleek@cross-solution.de
 */

/* @var \Core\Options\ModuleOptions $options */
$options = $this->services('Core/Options');
$siteName = $options->getSiteName();
$operator = $options->getOperator();

/** @var \Zend\View\Renderer\PhpRenderer $this */
/** @var \Zend\View\Helper\ServerUrl $serverUrl */
$serverUrl = $this->plugin('serverUrl');
$serverUrl->setHost($this->host)
    ->setScheme($this->scheme);
/** @var \Zend\View\Helper\BasePath $basePath */
$basePath = $this->plugin('basePath');
$basePath->setBasePath($this->basePath);
/** @var \Zend\Mvc\Router\Http\TreeRouteStack $router */
$router = $this->services('HttpRouter');
$router->setBaseUrl($this->basePath);
/** @var \JobsByMail\Entity\SearchProfileInterface $searchProfile */
$searchProfile = $this->searchProfile;

/** @var \JobsByMail\Service\Hash $hash */
$hash = $this->hash;
$lang = $searchProfile->getLanguage();
$unsubscribeUrl = $this->serverUrl(
    $this->url('lang/jobsbymail/unsubscribe',
               [
                   'lang' => $lang,
                   'id' => $searchProfile->getId(),
                   'hash' => $hash->generate($searchProfile)
               ]
    )
);

$homepageUrl=$this->serverUrl($this->basePath('/'));

?>
<body>
    <?=$this->partial('mail/header',[
        'title' => sprintf($this->translate('new jobs since %s'), $this->dateFormat($searchProfile->getDateLastMail(), 'short', 'none')),
    ])
    ?>


    <table style="width:100%;background:#f3f3f3;padding:0;border-spacing:0;font-family:Helvetica,Arial,sans-serif;font-size:14px;font-weight:200;line-height:1.3;vertical-align:top;">
        <tr>
            <td style="width:5%;vertical-align:top;padding:0;">
                <div style="background-color: #2F70AC; color: #FFFFFF;">
                    <table style="border-spacing:0;padding:0;width:100%">
                        <tbody>
                        <tr>
                            <td height="400px" style="height:400px;border-collapse: collapse!important;margin:0;mso-line-height-rule:exactly;padding:0;">&nbsp;</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </td>
            <td style="vertical-align:top;padding:0;font-family:Helvetica,Arial ,sans-serif;">
                <table align="center" style="background-color:#2F70AC;color:#FFFFFF;border-spacing:0;margin:0;padding:0;text-align:inherit;vertical-align:top;width:100%">
                    <tbody>
                    <tr>
                        <td style="border-collapse:collapse!important;color:#0a0a0a ;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:normal">
                            <br>

                            <center style="background-color:#2F70AC;color:#FFFFFF;font-size:22px;font-weight:400;">Seit deinem letzten Besuch</center>

                            <!--

@todo: maybe we can add things like "new jobs since", "new companies since" .....


<table style="table-layout:fixed;margin:10px 0 20px 0;padding:0;vertical-align:top;width:100%">
    <tbody>
    <tr>
        <td style="text-align:center;font-size:36px;font-weight:400;">
            <a href="https://forum.yawik.org/new" style="text-decoration:none;font-weight:bold;background-color:#2F70AC;color:#FFFFFF;"><strong>3</strong></a>
        </td>
        <td style="text-align:center;font-size:36px;font-weight:400;">
            <a href="https://forum.yawik.org/about" style="text-decoration:none;font-weight:bold;background-color:#2F70AC;color:#FFFFFF;"><strong>3</strong></a>
        </td>
    </tr>
    <tr>
        <td style="font-size:14px;font-weight:400;text-align:center;">
            <a href="https://forum.yawik.org/new" style="text-decoration:none;font-weight:bold;background-color:#2F70AC; color: #FFFFFF;"><strong>Neue Themen</strong></a>
        </td>
        <td style="font-size:14px;font-weight:400;text-align:center;">
            <a href="https://forum.yawik.org/about" style="text-decoration:none;font-weight:bold;background-color:#2F70AC;color: #FFFFFF;"><strong>Neue Benutzer</strong></a>
        </td>
    </tr>
    </tbody>
</table>
-->
                            <center style="background-color:#2F70AC;color:#FFFFFF;font-size:22px;font-weight:400;margin-bottom: 8px;">
                                <?php $query=$searchProfile->getQuery()?>
                                <?= sprintf($this->translate("New Jobs for \"%s\""),$query['q'])?>
                            </center>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <table align="center" style="border-spacing:0;background:#fefefe;margin:0;padding:0;text-align:center;vertical-align:top;width:100%">
                    <tbody>
                    <tr>
                        <td style="-moz-hyphens:auto;-webkit-hyphens:auto;border-collapse:collapse!important;color:#0a0a0a;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:normal">

                        <?php foreach ($this->jobs as $job): /** @var \Jobs\Entity\Job $job */ ?>
                        <?php

                        $jobUrl = $this->jobUrl($job, ['linkOnly' => true, 'absolute' => true], ['lang' => $lang]);
                        $organization = $job->getOrganization();
                        $hasOrganization = $organization && is_object($organization->getOrganizationName());

                        ?><!--   Beginning of new jobs   -->
                            <table style="width:100%">
                                <tbody>
                                <tr>
                                    <td style="margin:0;padding:0 0 0 16px;text-align:left;vertical-align:top;">
                                        <p style="color:#8f8f8f;line-height:1.3;margin: 20px 0 0 0;">
                                            <a href="https://forum.yawik.org/c/faq" style="text-decoration:none;font-weight: bold; color: #006699; font-size: 0.857em; white-space: nowrap; display: inline-block; position:relative; line-height:1; margin-right:10px;">
                                                <span style="background-color:#AB9364;display:inline-block;width:10px;height:10px;"></span>
                                                <span style="color:#222222 !important; vertical-align: text-top; line-height: 1;margin-left:4px;padding-left:2px;display:inline;max-width:150px;overflow: hidden;text-overflow:ellipsis;" data-drop-close="true">
                                                    <?php if($job->getClassifications() && $job->getClassifications()->getProfessions()):?>
                                                    <ul>
                                                    <?php
                                                    foreach( $job->getClassifications()->getProfessions()->getItems() as $profession) {
                                                        echo '<li>'.$profession->getName().'</li>';
                                                    }
                                                    ?>
                                                    </ul>
                                                    <?php endif?>
                                                </span>
                                            </a>
                                        </p>
                                    </td>
                                    <td style="margin:0;padding: 0 16px 0 0;text-align:right;vertical-align:top;">
                                        <p style="color:#8f8f8f;line-height:1.3;margin:20px 0 0 0;font-weight:400;">
                                            <?php
                                            if ($job->getDatePublishStart()): echo $this->dateFormat($job->getDatePublishStart(), 'short', 'none');
                                            elseif ($job->getDateCreated()): echo $this->dateFormat($job->getDateCreated(), 'short', 'none');
                                            endif
                                            ?>
                                        </p>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                            <table style="vertical-align:top;width:100%">
                                <tbody>
                                <tr>
                                    <td style="padding: 0 8px 8px 16px; text-align:left; width:100%;" >
                                        <h2 style="font-size:18px;font-weight:400;line-height:1.3;margin:0;padding:0;word-wrap:normal">
                                            <a href="<?=$jobUrl?>" style="text-decoration: none; font-weight:bold;color:#006699;font-weight:400;line-height:1.3;margin:0;padding:0;text-decoration:none">
                                                <strong><?=$job->getTitle()?></strong>
                                            </a>
                                        </h2>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                            <table style="padding:0;position:relative;text-align:left;vertical-align:top;width:100%">
                                <tbody>
                                <tr>
                                    <td style="color:#0a0a0a;line-height:1.3;margin:0 auto;padding:0  0 0 16px;width:50px;">
                                        <?php if ($hasOrganization && $organization->getImage()): ?>
                                            <div><img src="<?=$this->serverUrl($this->basePath($this->organizationImageCache->getUri($organization->getImage(true))))?>" height="80"></div>
                                        <?php endif ?>
                                    </td>
                                    <td style="color:#0a0a0a;padding:0 16px 0 8px;text-align:left;vertical-align:top;">
                                        <h6 style="color:inherit;line-height:1.3;margin:0;padding:0 ;font-weight: normal;font-size:16px;">
                                            <?php if ($hasOrganization && $organization->getOrganizationName()->getName()): ?>
                                                <?=$organization->getOrganizationName()->getName()?>
                                            <?php endif ?>
                                        </h6>
                                        <p style="color:inherit;font-size:14px;font-weight:400;line-height:1.3;margin:0 0 8px 0;padding:0;word-wrap:normal;">
                                            <?=$job->getLocation()?>
                                        </p>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                            <table style="border-bottom:1px solid #f3f3f3;padding:0;text-align:left;vertical-align:top;width:100%">
                                <tbody>
                                <tr>
                                    <td style="color:#0a0a0a;font-size:14px;padding:0 16px 0 16px;text-align:left;width:100%;font-weight:normal;">
                                        <p>
                                            <?php if($job->getTemplateValues()):?>
                                                <?=strip_tags($job->getTemplateValues()->getRequirements())?>
                                            <?php endif;?>
                                        </p>
                                    </td>
                                </tr>
                                </tbody>
                            </table>

                            <table style="padding:0;text-align:left;vertical-align:top;width:100%;  margin-top:20px;">
                                <tbody>
                                <tr>
                                    <!--

                                    @todo: maybe we can add links to apply or to forward jobs....

                                    <td style="padding:0 8px 16px 16px;text-align:left;white-space:nowrap;vertical-align:top;width:75px">
                                        <img src="https://forum.yawik.org/images/emails/heart.png"  style="clear:both;display:inline-block;float:left;height:20px;margin:0;max-width:100%;opacity:.4;outline:0;text-decoration:none;width:auto">
                                        <p style="color:#8f8f8f;float:left;line-height:1.3;margin:0 5px  10px 5px;padding:0;text-align:left;font-weight:400;">0</p>
                                    </td>
                                    <td style="padding:0 8px 16px 8px;text-align:left;white-space:nowrap;vertical-align:top;width:75px">
                                        <img src="https://forum.yawik.org/images/emails/comment.png " style="clear:none;display:inline-block;float:left;height:20px;margin: 0;max-width:100%;opacity:.4;outline:0;text-decoration:none;width:auto">
                                        <p style="color:#8f8f8f;float:left;line-height:1.3;margin:0 5px  10px 5px;padding:0;text-align:left;font-weight:400;">0</p>
                                    </td>
                                    <td style="padding:0 8px 16px 8px;text-align:left;white-space:nowrap;vertical-align:top;">
                                        <img src="https://forum.yawik.org/user_avatar/forum.yawik.org/cbleek/45/2_1.png" style="border-radius:50%;clear:both;display:inline-block;height:20px;width:20px;outline:0;text-decoration:none;">
                                    </td>
                                    -->
                                    <td style="line-height:1.3;padding:0 16px 0 8px;text-align:right; white-space:nowrap;vertical-align:top;">
                                        <a href="<?=$jobUrl?>" style="text-decoration:none;font-weight:bold;background-color:#2F70AC;color:#FFFFFF;width:100%;text-decoration:none;padding:8px 16px;white-space:nowrap;">
                                            Mehr lesen
                                        </a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <div style="background-color:#f3f3f3;">
                                <table style="padding:0;width:100%">
                                    <tbody><tr><td height="20px" style="border-collapse:collapse!important;line-height:20px;margin:0;mso-line-height-rule:exactly;padding:0;">&nbsp;</td></tr></tbody>
                                </table>
                            </div>
                            <!--   End of new jobs   -->

                            <?php endforeach;?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </td>
            <td style="width:5%;vertical-align:top;padding:0;">
                <!-- Background that goes down part-way behind content -->
                <div style="background-color:#2F70AC;color: #FFFFFF;">
                    <table style="border-spacing:0;padding:0;width:100%">
                        <tbody>
                        <tr>
                            <td height="400px" style="height:400px;border-collapse:collapse!important;margin:0;mso-line-height-rule:exactly;padding:0;"></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </td>
        </tr>
    </table>

    <td style="width:5%;padding:0;">&nbsp;</td>

    <style>
        @media only screen {
            html {
                min-height: 100%;
                background: #f3f3f3
            }
        }

        @media only screen and (max-width:900px) {
            table.body img {
                width: auto;
                height: auto
            }
            table.body center {
                min-width: 0!important;
            }
            table.body .side-spacer {
                width: 2.5%!important;
            }
            table.body .column,
            table.body .columns {
                height: auto!important;
                -moz-box-sizing: border-box;
                -webkit-box-sizing: border-box;
                box-sizing: border-box;
                padding-left: 16px!important;
                padding-right: 16px!important
            }
            table.body .column .column,
            table.body .column .columns,
            table.body .columns .column,
            table.body .columns .columns {
                padding-left: 0!important;
                padding-right: 0!important
            }
        }
    </style>

    <div style="color:#666; font-size:95%; text-align:center; padding-top:15px;">
        Diese Zusammenfassung wird von <a href="<?=$homepageUrl?>" style="text-decoration:none;font-weight:bold;color:#0088cc"><?=$siteName?></a> gesendet, wenn wir dich einige Zeit lang nicht gesehen haben. Abbestellen unter <a style="text-decoration: none;font-weight:bold;color:#0088cc" href="<?=$unsubscribeUrl?>">klicke hier</a>.
    </div>

    <!-- prevent Gmail on iOS font size manipulation -->
    <div style="display:none;white-space:nowrap;font:15px courier;line-height:0">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>

    <?=$this->partial('mail/footer') ?>

</body>