<?php
$form = $this->element;
?>
<p>
    <button class="btn btn-info" data-title="<?=$this->translate('Send me jobs by email')?>" data-toggle="modal" data-target="#job-by-mail-subscribe-modal" title="<?=$this->translate('Send me jobs by email')?>">
        <i class="yk-icon yk-icon-envelope"></i>
        <?php echo $this->translate("Send me jobs by email");?>
    </button>
</p>
<div id="job-by-mail-subscribe-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="job-by-mail-subscribe-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <?=$this->form()->openTag($form)?>
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="job-by-mail-subscribe-label"><?=$this->translate('Get the right Job via e-mail')?></h3>
                </div>
                <div class="modal-body">
                        <?=$this->formElement($form->get('email')->setAttributes(
                            [
                                'class' => 'form-control ',
                                'placeholder' => $this->translate('Enter your email address'),
                            ]
                        ))?>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?=$this->translate('Cancel') ?></button>
                    <button class="btn btn-primary" type="submit"><?=$this->translate('Subscribe') ?></button>
                </div>
            <?=$this->form()->closeTag()?>
        </div>
    </div>
</div>